#!/bin/bash
CYAN='\033[1;36m'; RESET='\033[0m'; GREEN='\033[32m'; RED='\033[31m'
menu(){ clear; title="The Broken Hourglass — Date & Time Tools"; echo -e "${CYAN}${title}${RESET}"; mapfile -t L< <(printf "%s\n" "Display Date/Time" "Change Date" "Change Time" "Sync NTP" "Change Time Zone" "Manage Hardware Clock" "Toggle Auto Sync" "Exit"); n=${#L[@]}; mid=$(( (n+1)/2 )); lw=0; for((i=0;i<mid;i++));do s="$((i+1)). ${L[i]}"; ((${#s}>lw))&&lw=${#s}; done; echo; for((i=0;i<mid;i++));do left="$((i+1)). ${L[i]}"; j=$((i+mid)); if((j<n));then right="$((j+1)). ${L[j]}"; printf "%-*s  %s\n" $lw "$left" "$right"; else printf "%s\n" "$left"; fi; done; echo; read -p "Choice: " c; case $c in 1) show_dt ;; 2) set_dt date ;; 3) set_dt time ;; 4) sync_ntp ;; 5) set_tz ;; 6) hw_clock ;; 7) toggle_sync ;; 8) exit ;; *) menu ;; esac; }
show_dt(){ clear; echo -e "${CYAN}Date: $(date)\nHardware: $(sudo hwclock 2>/dev/null||echo n/a)\nSync: $(timedatectl show -p NTPSynchronized --value)${RESET}"; read -n 1 -s -r -p "Press any key..."; menu; }
set_dt(){ clear; read -p "New $1 (YYYY-MM-DD for date, HH:MM:SS for time): " v; [[ $v =~ ^([0-9]{4}-[0-9]{2}-[0-9]{2}|[0-9]{2}:[0-9]{2}:[0-9]{2})$ ]] && sudo date -s "$v" && echo -e "${GREEN}$1 updated.${RESET}" || echo -e "${RED}Invalid format.${RESET}"; read -n 1 -s -r -p "Press any key..."; menu; }
sync_ntp(){ clear; echo -e "${CYAN}Syncing NTP...${RESET}"; if command -v ntpdate &>/dev/null; then sudo ntpdate pool.ntp.org && echo -e "${GREEN}NTP synced.${RESET}"; else sudo timedatectl set-ntp true && echo -e "${GREEN}Systemd-timesyncd enabled.${RESET}"; fi; read -n 1 -s -r -p "Press any key..."; menu; }
set_tz(){ clear; echo -e "${CYAN}Current TZ: $(timedatectl show -p Timezone --value)${RESET}"; read -p "List all time zones? (y/n): " a; [[ $a == y ]] && timedatectl list-timezones | less; read -p "New TZ: " tz; timedatectl set-timezone "$tz" &>/dev/null && echo -e "${GREEN}Time zone updated.${RESET}" || echo -e "${RED}Invalid time zone.${RESET}"; read -n 1 -s -r -p "Press any key..."; menu; }
hw_clock(){ clear; echo -e "${CYAN}Hardware Clock: $(sudo hwclock 2>/dev/null||echo n/a)${RESET}"; echo "1) Sync HW → System  2) Sync System → HW  3) Back"; read -p "Choice: " c; case $c in 1) sudo hwclock --hctosys ;; 2) sudo hwclock --systohc ;; 3) ;; *) echo -e "${RED}Invalid.${RESET}";; esac; read -n 1 -s -r -p "Press any key..."; menu; }
toggle_sync(){ clear; state="$(timedatectl show -p NTP --value)"; echo -e "${CYAN}Auto Sync: $state${RESET}"; read -p "Toggle? (y/n): " c; if [[ $c == y ]]; then if [[ $state == yes ]]; then sudo timedatectl set-ntp false; else sudo timedatectl set-ntp true; fi; echo -e "${GREEN}Sync toggled.${RESET}"; fi; read -n 1 -s -r -p "Press any key..."; menu; }
menu
